# Generated by Django 5.2.17 on 2026-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.CharField(choices=[('budget', 'Budget'), ('moderate', 'Moderate'), ('luxary', 'Luxury')], max_length=10),
        ),
    ]
